## 4.File Handling and String Formating agenda:
* [File Handling](#file_handling)
* [Exercise 1](#ex1)
* [String Formating](#string_formating)

    * [Method 0 Concatenating](#method_0)
    * [Method 0 Modulo %](#method_1)
    * [Method 0 .format()](#method_2)
    * [Method 0 f-string](#method_3)
* [Exercise 2](#ex2)

    


## <a id='file_handling'></a>**File Handling**
In real apps we take inputs from users. The inputs can be a button click (Computers) , voice (Phone assistant), text files, or any other forms.

In this chapter we will discuss how to deal with text files with Python

In [1]:
# variable 'f' is a file handle : a variable that points to (stores) the address of the file
f = open("words.txt", encoding = "utf-8")
# do file operations 
lines = f.readlines()

for i,line in enumerate(lines):
    if i == 10:
        break
    print(i,line)
    
# It's important to close the file after editing,
# otherwise the changes won't be saved to the file
# also as long as the file is open, the OS will restrict any other access to the file
f.close()


0 2

1 

2 1080

3 

4 &c

5 

6 10-point

7 

8 10th

9 



In [17]:
help(open)

Help on built-in function open in module io:

open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
    Open file and return a stream.  Raise OSError upon failure.
    
    file is either a text or byte string giving the name (and the path
    if the file isn't in the current working directory) of the file to
    be opened or an integer file descriptor of the file to be
    wrapped. (If a file descriptor is given, it is closed when the
    returned I/O object is closed, unless closefd is set to False.)
    
    mode is an optional string that specifies the mode in which the file
    is opened. It defaults to 'r' which means open for reading in text
    mode.  Other common values are 'w' for writing (truncating the file if
    it already exists), 'x' for creating and writing to a new file, and
    'a' for appending (which on some Unix systems, means that all writes
    append to the end of the file regardless of the current seek position

A better code does error handling. What if the file we are trying to open doesn't exists?

In [9]:
try:
    f = open("wordss.txt", encoding = "utf-8")
    lines = f.readlines()

    for i,line in enumerate(lines):
        if i == 10:
            break
        print(line)
        
except FileNotFoundError:
    print("open the correct file")
    
    
    
finally:
    f.close()


open the correct file


using with statement 

In [13]:
with open("words.txt", encoding = "utf-8") as f:
    lines = f.readlines()
    for i,line in enumerate(lines):
        if i == 10:
            break
        print(line)


2



1080



&c



10-point



10th





write in a file using write() method

In [ ]:
with  open("file.txt", "w", encoding = "utf-8") as f:
    f.write("my first line\n")
    f.write("this is the second line\n") 

In [ ]:
with  open("file.txt", "r", encoding = "utf-8") as f:
    for line in f:
        print (line)

my first line

this is the second line



Opening a file in write mode will clear its content if exists

In [ ]:
with  open("file.txt", "r", encoding = "utf-8") as f:
    for line in f:
        print (line, end = " ")

Using readline() method to read lines progressively in a loop

In [ ]:
with  open("words.txt", "r", encoding = "utf-8") as f:
    for i in range(5):
        print(f.readline())


2

1080

&c

10-point

10th



Opening files in append mode to save its content and append only at the end

In [ ]:
with  open("file.txt", "w", encoding = "utf-8") as f:
    f.write("my first line\n")
    f.write("this is the second line\n") 

In [ ]:
with  open("file.txt", "a", encoding = "utf-8") as f:
    f.write("this is the third line\n") 

In [ ]:
with  open("file.txt", "r", encoding = "utf-8") as f:
    for line in f:
        print (line)

my first line

this is the second line

this is the third line



## <a id='ex1'></a>**Exercise 1**
A common file formate is a **CSV** file, its used to represent tables.    
* every entry in the same row in the table is seperated by (**,**).    
* evey line represents a row in the table.

heres an exmaple of how a csv file looks
```
row_1col_1,row1_col2,row1_col3    
row_2col_1,row2_col2,row2_col3    
row_2col_1,row2_col2,row2_col3    
```
Your task is to:   
1- write a csv file where:
  * first row has 2 entries **name** and **age**.
  * write 5 rows with random names and random ages.

2- read this file in a **2D list**
  * each row is a list where each entity is an element in this list.
  * One list will contains all the lists
 


In [ ]:
# create the file and write it 


# read the file and parse it



## **Encoding**

Computers understand binary (0's 1's). Encoding means giving every character a certain binary code. When the computer gets the binary code (lets say for letter 'A') it understands that it should display the letter 'A'.

A basic encoding is the ASCII which encodes only 128 character. Since this is very limited we had to think of other encodings that include non English characters such as Arabic letters or even Emoji.

UTF-8 encodes 1,112,064 different characters

## <a id='string_formating'></a> **String Formatting**

In this part we will discuss how to handle and print strings in a better and elegant way.

## **Injecting an item**

So far we have been adding a variable to a string using concatenation but this makes the code less readable and maintainable.

In this section we will discuss 3 other ways

### <a id='method_0'></a> **Method 0: Concatenation**

This is the old way. As you can see we have to remember carefully where to put spaces to avoid the issue below "GoodeveningHoda". If the number of items we want to inject is large this will cause a greater headache!.

This is just one issue with this method, other issues will appear when we discuss the other ways

In [10]:
name = "Hoda"
time = "evening"
my_bad_str = "Good" + time + name

print (my_bad_str)

GoodeveningHoda


In [11]:
my_good_str = "Good " + time + " " + name
print (my_good_str)

Good evening Hoda


### <a id='method_1'></a> **Method 1: modulo %**

In this method we add a modulo character where we want to add the string 

In [33]:
name = "Hoda"
time = 1
my_modulo_str = "Good %d %s" %(time,name)

print (my_modulo_str)

Good 1 Hoda


%s is called string conversion and indicates that in this place we are going to add a **s**tring.

Other conversion:


```
Conversion	Meaning
d	Signed integer decimal.
i	Signed integer decimal.
o	Unsigned octal.
u	Obsolete and equivalent to 'd', i.e. signed integer decimal.
x	Unsigned hexadecimal (lowercase).
X	Unsigned hexadecimal (uppercase).
e	Floating point exponential format (lowercase).
E	Floating point exponential format (uppercase).
f	Floating point decimal format.
F	Floating point decimal format.
g	Same as "e" if exponent is greater than -4 or less than precision, "f" otherwise.
G	Same as "E" if exponent is greater than -4 or less than precision, "F" otherwise.
c	Single character (accepts integer or single character string).
r	String (converts any python object using repr()).
s	String (converts any python object using str()).
%	No argument is converted, results in a "%" character in the result.
```




Lets experiment more with floating point conversion!

As you can see we replaced the placeholder %f with the integer "score" however the string contained the float "88.000000" because the placeholder did floating conversion.

Also notice how we can add several placeholders withe different types in the same string

In [13]:
name = "Ali"
score = 88

my_modulo_str = "%s score is: %f" %(name,score)

print (my_modulo_str)

Ali score is: 88.000000


Controlling the floating point precision:
%8.4f means : the number should take at least 8 characters if there are less then %f will add spaces to the left

**.4f** means : the number should have 4 digits after the decimal point. If there are less digits %f will add zeros to the right

In our case "score" had 7 characters
 ( + 1 

*   2 numbers before the decimal
*   4 numbers after the decimal (not 3 because we specified .4f after the decimal point)
*   1 decimal point "."

but since we specified a conversion of 7 characters %f added a space to the right

We have 3 digits after the decimal point .456 so %f padded 1 zero to make them 4


In [37]:
name = "Ali"
score = 88.456

my_modulo_str = "%s score is:%8.9f" %(name,score)

print (my_modulo_str)

Ali score is:88.456000000


Notice that if the precision %7.1f the conversion will remove the last digit and does rounding 88.456 -> 88.5

In [ ]:
name = "Ali"
score = 88.456

my_modulo_str = "%s score is:%7.1f" %(name,score)

print (my_modulo_str)

Ali score is:   88.5


### <a id='method_2'></a> **Method 2: .format()**

This method is very similar to the modulo method but with more features

In [14]:
name = "Hoda"
time = "evening"
my_format_str = "Good {} {}".format(time, name)

print (my_format_str)

Good evening Hoda


#### **Using Index**

The first added feature is injected items can be called by index instead of position

In [15]:
name = "Hoda"
time = "evening"
my_format_str = "Good {1} {0}".format(name, time)

print (my_format_str)

Good evening Hoda


#### **Keyword index**

Another feature is giving the injected items keywords and passing it using them

In [16]:
name = "Hoda"
time = "evening"
my_format_str = "Good {time_of_day} {n}".format(n=name, time_of_day=time)

print (my_format_str)

Good evening Hoda


You can also use the injected item several times either with numbers or keywords

In [17]:
name = "Hoda"
time = "evening"
my_format_str = "Welcoming {n}...\nGood {time_of_day} {n}".format(n=name, time_of_day=time)

print (my_format_str)

Welcoming Hoda...
Good evening Hoda


#### **Floating point**

{1:7.1f} : means for the item of index 1 format it to 7.1f

In [18]:
name = "Ali"
score = 88.456

my_modulo_str = "%s score is:%7.1f" %(name,score)
my_format_str =  "{0} score is:{1:7.1f}".format(name,score)

print (my_modulo_str)
print (my_format_str)


Ali score is:   88.5
Ali score is:   88.5


#### **Alignment and Padding**

Now our strings are going to get real pretty

Ever wondered how to print tables like this:

```
Name      | Score
Amr       | 78.2
Hoda      | 88.5
Zainab    | 82.6
```

The first thought is to keep adding spaces to get things aligned, but with Python we can do that easily

In [19]:
names_scores_dict = {'Amr':78.2,
                     'Hoda':88.5,
                     'Zainab':82.6}

print('{0:10} | {1:10}'.format('Name', "Score"))
for name, score in names_scores_dict.items():
  print('{0:10} | {1:10}'.format(name, score))

Name       | Score     
Amr        |       78.2
Hoda       |       88.5
Zainab     |       82.6


Lets make it better! 
We want to align the word Score to the right along with the numbers

The arrow sign > , < or ^ tells .format where to align the string

\> : align to the left

< : align to the right

^ : align to the center

In [ ]:
names_scores_dict = {'Amr':78.2,
                     'Hoda':88.5,
                     'Zainab':82.6}

print('{0:10} | {1:>10}'.format('Name', "Score"))
for name, score in names_scores_dict.items():
  print('{0:10} | {1:>10}'.format(name, score))

Name       |      Score
Amr        |       78.2
Hoda       |       88.5
Zainab     |       82.6


By default .format pads strings with spaces but you can change that to any character

Lets pad the header with '.' instead.

In [ ]:
names_scores_dict = {'Amr':78.2,
                     'Hoda':88.5,
                     'Zainab':82.6}

print('{0:.<10} | {1:.>10}'.format('Name', "Score"))
for name, score in names_scores_dict.items():
  print('{0:10} | {1:>10}'.format(name, score))

Name...... | .....Score
Amr        |       78.2
Hoda       |       88.5
Zainab     |       82.6


### <a id='method_3'></a> **Method 3: f-strings**

F-strings have several advantages over .format().

Lets see them!

In the example below we injected the items immediately into the string. This is way more readable than other methods

In [ ]:
name = "Hoda"
time = "evening"
my_f_str = f"Good {time} {name}"

print (my_f_str)

Good evening Hoda


#### **Floating point**
The syntax for injecting floating point is:

{item:{width}.{precision}}

The difference here is that precision is the total number of all digits before and after the decimal point.


In [ ]:
name = "Ali"
score = 88.456

my_format_str = "{0} score is:{1:7.1f}".format(name,score)
my_f_str = f"{name} score is:{score:{7}.{4}}"

print (my_format_str)
print (my_f_str)

Ali score is:   88.5
Ali score is:  88.46


## <a id='ex2'></a>**Exercise 2**

**Hi my name is "name-> string", I am "age->int" years old, my heigth is "height->float" meters.**

wirte the previos string using each of the 3 formating methods explained above.
* you should use the given variables in the code block.
* you should use **2 numbers** after the decimal point.





In [ ]:
# print the string using "module" methods

# print the string using ".format()" methods

# print the string using  "f-strings" methods
